### ISSUE TITLE
In the preprocessing.py, when creating subsets,  it seems there's no operation about the discarded sequence?

### ISSUE THREAD

**Issue by plantonic** [FilippoMB/Ensemble-Conformalized-Quantile-Regression#2]

**Comment by FilippoMB** [comment]
You are right, thanks! I now modified [line 93](https://github.com/FilippoMB/Ensemble-Conformalized-Quantile-Regression/blob/fbba4a3927b7ad91e582623b75691d151ccd57fb/data_preprocessing.py#L93) and [line 96](https://github.com/FilippoMB/Ensemble-Conformalized-Quantile-Regression/blob/fbba4a3927b7ad91e582623b75691d151ccd57fb/data_preprocessing.py#L96) in data_preprocessing.py

I recently did a major restructuring to the code and the deletion part slipped out.
